### ISSUE TITLE
Oracle APIs Postman Collection

### ISSUE THREAD

**Issue by Sarkie** [Loadium/postman2jmx#21]
Hi,

Getting exceptions with most of these

https://github.com/oracle/hospitality-api-docs/tree/main/postman-collections

```
[23-Jan-19 12:17:17:671] [INFO] [Postman2Jmx:33] - Trying to build jmx file: workflows.jmx
[23-Jan-19 12:17:17:704] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'jmeterengine.threadstop.wait', defaulting to: 5000
[23-Jan-19 12:17:17:704] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'jmeterthread.rampup.granularity', defaulting to: 1000
[23-Jan-19 12:17:17:719] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'httpsampler.max_bytes_to_store_per_request', defaulting to: 0
[23-Jan-19 12:17:17:719] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'httpsampler.max_buffer_size', defaulting to: 66560
[23-Jan-19 12:17:17:719] [WARN] [JMeterUtils:730] - Exception 'null' occurred when fetching boolean property:'httpsampler.ignore_failed_embedded_resources', defaulting to: false
[23-Jan-19 12:17:17:719] [WARN] [JMeterUtils:730] - Exception 'null' occurred when fetching boolean property:'httpsampler.embedded_resources_use_md5', defaulting to: false
[23-Jan-19 12:17:17:720] [WARN] [JMeterUtils:794] - Exception 'null' occurred when fetching String property:'httpsampler.user_defined_methods', defaulting to:
[23-Jan-19 12:17:17:723] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'httpsampler.max_redirects', defaulting to: 20
[23-Jan-19 12:17:17:723] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'httpsampler.max_frame_depth', defaulting to: 5
[23-Jan-19 12:17:17:723] [WARN] [JMeterUtils:812] - Exception 'null' occurred when fetching String property:'HTTPResponse.parsers'
[23-Jan-19 12:17:17:723] [WARN] [JMeterUtils:730] - Exception 'null' occurred when fetching boolean property:'httpsampler.redirect.removeslashdotdot', defaulting to: true
[23-Jan-19 12:17:17:724] [WARN] [JMeterUtils:730] - Exception 'null' occurred when fetching boolean property:'httpsampler.separate.container', defaulting to: true
[23-Jan-19 12:17:17:736] [ERROR] [Postman2Jmx:39] - Error occurred!
java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.jmeter.testelement.property.AbstractProperty.<init>(AbstractProperty.java:40) ~[ApacheJMeter_core-4.0.jar:4.0 r1823414]
        at org.apache.jmeter.testelement.property.MultiProperty.<init>(MultiProperty.java:36) ~[ApacheJMeter_core-4.0.jar:4.0 r1823414]
        at org.apache.jmeter.testelement.property.TestElementProperty.<init>(TestElementProperty.java:31) ~[ApacheJMeter_core-4.0.jar:4.0 r1823414]
        at org.apache.jmeter.config.Arguments.addArgument(Arguments.java:119) ~[ApacheJMeter_core-4.0.jar:4.0 r1823414]
        at com.loadium.postman2jmx.model.jmx.JmxHTTPSamplerProxy.newInstance(JmxHTTPSamplerProxy.java:88) ~[Postman2Jmx.jar:?]
        at com.loadium.postman2jmx.builder.JmxRawBodyBuilder.buildJmxBody(JmxRawBodyBuilder.java:18) ~[Postman2Jmx.jar:?]
        at com.loadium.postman2jmx.builder.AbstractJmxFileBuilder.buildJmxFile(AbstractJmxFileBuilder.java:62) ~[Postman2Jmx.jar:?]
        at com.loadium.postman2jmx.builder.JmxFileBuilder.build(JmxFileBuilder.java:10) ~[Postman2Jmx.jar:?]
        at com.loadium.postman2jmx.app.Postman2Jmx.main(Postman2Jmx.java:35) [Postman2Jmx.jar:?]
```

and
```
[23-Jan-19 12:15:10:605] [INFO] [Postman2Jmx:33] - Trying to build jmx file: test.jmx
[23-Jan-19 12:15:10:659] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'jmeterengine.threadstop.wait', defaulting to: 5000
[23-Jan-19 12:15:10:660] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'jmeterthread.rampup.granularity', defaulting to: 1000
[23-Jan-19 12:15:10:675] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'httpsampler.max_bytes_to_store_per_request', defaulting to: 0
[23-Jan-19 12:15:10:676] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'httpsampler.max_buffer_size', defaulting to: 66560
[23-Jan-19 12:15:10:676] [WARN] [JMeterUtils:730] - Exception 'null' occurred when fetching boolean property:'httpsampler.ignore_failed_embedded_resources', defaulting to: false
[23-Jan-19 12:15:10:676] [WARN] [JMeterUtils:730] - Exception 'null' occurred when fetching boolean property:'httpsampler.embedded_resources_use_md5', defaulting to: false
[23-Jan-19 12:15:10:677] [WARN] [JMeterUtils:794] - Exception 'null' occurred when fetching String property:'httpsampler.user_defined_methods', defaulting to:
[23-Jan-19 12:15:10:680] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'httpsampler.max_redirects', defaulting to: 20
[23-Jan-19 12:15:10:681] [WARN] [JMeterUtils:703] - Exception 'null' occurred when fetching int property:'httpsampler.max_frame_depth', defaulting to: 5
[23-Jan-19 12:15:10:681] [WARN] [JMeterUtils:812] - Exception 'null' occurred when fetching String property:'HTTPResponse.parsers'
[23-Jan-19 12:15:10:681] [WARN] [JMeterUtils:730] - Exception 'null' occurred when fetching boolean property:'httpsampler.redirect.removeslashdotdot', defaulting to: true
[23-Jan-19 12:15:10:681] [WARN] [JMeterUtils:730] - Exception 'null' occurred when fetching boolean property:'httpsampler.separate.container', defaulting to: true
[23-Jan-19 12:15:10:700] [ERROR] [Postman2Jmx:39] - Error occurred!
java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.jmeter.testelement.property.AbstractProperty.<init>(AbstractProperty.java:40) ~[ApacheJMeter_core-4.0.jar:4.0 r1823414]
        at org.apache.jmeter.testelement.property.MultiProperty.<init>(MultiProperty.java:36) ~[ApacheJMeter_core-4.0.jar:4.0 r1823414]
        at org.apache.jmeter.testelement.property.TestElementProperty.<init>(TestElementProperty.java:31) ~[ApacheJMeter_core-4.0.jar:4.0 r1823414]
        at org.apache.jmeter.config.Arguments.addArgument(Arguments.java:119) ~[ApacheJMeter_core-4.0.jar:4.0 r1823414]
        at com.loadium.postman2jmx.model.jmx.JmxHTTPSamplerProxy.newInstance(JmxHTTPSamplerProxy.java:88) ~[Postman2Jmx.jar:?]
        at com.loadium.postman2jmx.builder.JmxRawBodyBuilder.buildJmxBody(JmxRawBodyBuilder.java:18) ~[Postman2Jmx.jar:?]
        at com.loadium.postman2jmx.builder.AbstractJmxFileBuilder.buildJmxFile(AbstractJmxFileBuilder.java:62) ~[Postman2Jmx.jar:?]
        at com.loadium.postman2jmx.builder.JmxFileBuilder.build(JmxFileBuilder.java:10) ~[Postman2Jmx.jar:?]
        at com.loadium.postman2jmx.app.Postman2Jmx.main(Postman2Jmx.java:35) [Postman2Jmx.jar:?]
```

Thank you!

**Comment by Sarkie** [comment]
![image](https://user-images.githubusercontent.com/283203/215533168-326500ee-f1bf-43fa-abe7-6d0d304519a8.png)
