### ISSUE TITLE
Getting java error while generating jar file

### ISSUE THREAD

**Issue by dineshdeveloper3** [Loadium/postman2jmx#23]
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:989)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:592)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:514)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:483)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:429)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:382)
        at org.apache.jmeter.save.SaveService$XStreamWrapper.<init>(SaveService.java:82)
        at org.apache.jmeter.save.SaveService$XStreamWrapper.<init>(SaveService.java:80)
        at org.apache.jmeter.save.SaveService.<clinit>(SaveService.java:113)
        at com.loadium.postman2jmx.builder.AbstractJmxFileBuilder.buildJmxFile(AbstractJmxFileBuilder.java:104)
        at com.loadium.postman2jmx.builder.JmxFileBuilder.build(JmxFileBuilder.java:10)
        at com.loadium.postman2jmx.app.Postman2Jmx.main(Postman2Jmx.java:35)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @11e21d0e
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:181)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:175)
        at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:40)
        at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)

**Comment by skczhans** [comment]
I also encountered this problem

**Comment by hostersi-czerny-szymon** [comment]
Use JDK8 for maven and jar execution.
