### ISSUE TITLE
I encountered some problems

### ISSUE THREAD

**Issue by skczhans** [Loadium/postman2jmx#26]
After the compilation is completed, I encountered some problems when running and I don't know what to do.
`Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:989)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:592)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:514)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:483)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:429)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:382)
        at org.apache.jmeter.save.SaveService$XStreamWrapper.<init>(SaveService.java:82)
        at org.apache.jmeter.save.SaveService$XStreamWrapper.<init>(SaveService.java:80)
        at org.apache.jmeter.save.SaveService.<clinit>(SaveService.java:113)
        at com.loadium.postman2jmx.builder.AbstractJmxFileBuilder.buildJmxFile(AbstractJmxFileBuilder.java:106)
        at com.loadium.postman2jmx.builder.JmxFileBuilder.build(JmxFileBuilder.java:10)
        at com.loadium.postman2jmx.app.Postman2Jmx.main(Postman2Jmx.java:35)
Caused by: java.lang.reflect.Inam.XStream.<init>(XStream.java:429)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:382)
        at org.apache.jmeter.save.SaveService$XStreamWrapper.<init>(SaveService.java:82)
        at org.apache.jmeter.save.SaveService$XStreamWrapper.<init>(SaveService.java:80)
        at org.apache.jmeter.save.SaveService.<clinit>(SaveService.java:113)
        at com.loadium.postman2jmx.builder.AbstractJmxFileBuilder.buildJmxFile(AbstractJmxFileBuilder.java:106)
        at com.loadium.postman2jmx.builder.JmxFileBuilder.build(JmxFileBuilder.java:10)
        at com.loadium.postman2jmx.app.Postman2Jmx.main(Postman2Jmx.java:35)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @21a947fe
        at java.base/java.lang.reflecccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @21a947fe
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
        at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:40)
        at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
        ... 12 more`

**Comment by aojh111** [comment]
try simple logic in Postman's test.

**Comment by hostersi-czerny-szymon** [comment]
compile and run the jar using JDK8.
